/**
 * The iOS daily-dashboard widget.
 *
 * `ios/` is gitignored and regenerated by `expo prebuild`, so — exactly like
 * the Android widget — the only durable home for this is a config plugin that
 * writes the sources during prebuild.
 *
 * ## What this plugin does and does not do
 *
 * It writes the Swift sources and a matching Info.plist into
 * `ios/RepChampDailyWidget/`, so the extension's code is version-controlled
 * and regenerated on every prebuild.
 *
 * It does **not** create the Xcode target. Adding a second target means
 * rewriting `project.pbxproj` — a fragile, undocumented format where a bad
 * edit corrupts the project rather than failing loudly — and an App Extension
 * additionally needs an App Group entitlement, which needs an Apple Developer
 * team id. Neither is configured here (`app.json` has no `appleTeamId`), so a
 * plugin that claimed to wire this up would be writing a target that cannot
 * be signed.
 *
 * The honest seam is therefore: this plugin owns the *code*, and the target
 * is added once in Xcode (or by `expo-apple-targets` once a team id exists).
 * `WIDGET_SETUP_IOS.md` records the exact steps. Everything the extension
 * reads — the payload keys, the copy, the thresholds — comes from
 * `src/domain/dashboardSnapshot.ts` and is unit-tested there, so the Swift
 * below stays a renderer with no decisions of its own.
 *
 * ## What is inert today, stated plainly
 *
 * Three things must all land before this widget shows real numbers, and only
 * the first is written:
 *
 *   1. The Swift — done, and it compiles against the real SDKs.
 *   2. The Xcode target and the App Group — needs a team id.
 *   3. **An iOS publish path.** `services/partnerWidget.ts` returns null
 *      unless `Platform.OS === 'android'`, so the dashboard publish wired
 *      into Home is a no-op on the very platform this widget runs on. It
 *      needs a small native module writing to the App Group suite and
 *      calling `WidgetCenter.shared.reloadTimelines(ofKind:)`.
 *
 * Until (3) exists the widget renders `DashboardSnapshot.preview` and
 * refreshes only on its hourly timeline. That is why the provider's comment
 * does not claim a reload it never receives.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** The target name, the folder name, and the scheme all match. */
const TARGET = 'RepChampDailyWidget';

/**
 * The App Group the app and the widget share.
 *
 * An extension runs in its own process with its own container, so
 * `UserDefaults.standard` in the widget is *not* the app's — the group
 * suite is the only way the payload crosses. Inert until the group is
 * registered against a real team id; `defaults(for:)` falls back to standard
 * defaults so the widget still builds and renders its placeholder.
 */
const APP_GROUP = 'group.gg.repchamp.app';

const SNAPSHOT_KEY = 'repchamp.widget.dashboard.v1';

const WIDGET_SWIFT = `import WidgetKit
import SwiftUI

// The payload the app publishes. Mirrors DashboardSnapshot in
// src/domain/dashboardSnapshot.ts — every label is built and tested there, so
// nothing here decides what the athlete reads.
struct DashboardSnapshot: Decodable {
    var waterLabel: String = ""
    var waterPercent: Int = 0
    var waterMet: Bool = false
    var stepsLabel: String = ""
    var stepsPercent: Int = 0
    var stepsMet: Bool = false
    var stepsKnown: Bool = false
    var partnerLine: String = ""
    var headline: String = ""
    var updatedAt: Double = 0

    // Shown in the widget gallery, where the system renders the view without
    // ever calling the timeline provider. Without real-looking values the
    // card is hollow at the exact moment someone decides whether to add it.
    static let preview = DashboardSnapshot(
        waterLabel: "1.5 L", waterPercent: 75, waterMet: false,
        stepsLabel: "8,432", stepsPercent: 105, stepsMet: true,
        stepsKnown: true,
        partnerLine: "Sam had 1.5 L today",
        headline: "500 ml of water to go",
        updatedAt: Date().timeIntervalSince1970 * 1000
    )
}

enum SnapshotStore {
    // The app group's suite, falling back to standard defaults so the
    // extension still builds and previews before the group is registered.
    static func defaults() -> UserDefaults {
        UserDefaults(suiteName: "\${APP_GROUP}") ?? .standard
    }

    static func load() -> DashboardSnapshot? {
        guard let raw = defaults().string(forKey: "\${SNAPSHOT_KEY}"),
              let data = raw.data(using: .utf8),
              let decoded = try? JSONDecoder().decode(DashboardSnapshot.self, from: data)
        else { return nil }
        return decoded
    }
}

struct Entry: TimelineEntry {
    let date: Date
    let snapshot: DashboardSnapshot
    let isStale: Bool
}

struct Provider: TimelineProvider {
    // Twelve hours, matching DASHBOARD_STALE_AFTER_MS. A widget that shows
    // yesterday's numbers as if they were today's is worse than one that
    // admits it has lost touch.
    private static let staleAfter: TimeInterval = 12 * 60 * 60

    private func entry(at date: Date) -> Entry {
        guard let snap = SnapshotStore.load() else {
            return Entry(date: date, snapshot: .preview, isStale: false)
        }
        let age = date.timeIntervalSince1970 - (snap.updatedAt / 1000)
        return Entry(date: date, snapshot: snap, isStale: age > Self.staleAfter)
    }

    func placeholder(in context: Context) -> Entry {
        Entry(date: Date(), snapshot: .preview, isStale: false)
    }

    func getSnapshot(in context: Context, completion: @escaping (Entry) -> Void) {
        completion(entry(at: Date()))
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> Void) {
        // One entry now, refreshed in an hour.
        //
        // The hourly policy is currently the ONLY refresh path. The app does
        // not yet call WidgetCenter.reloadTimelines on publish, because the
        // iOS half of publishWidgetSnapshot does not exist — see the plugin
        // header. Until it does, a glass logged at 10:05 will not reach this
        // widget until the next timeline refresh.
        let now = Date()
        let next = Calendar.current.date(byAdding: .hour, value: 1, to: now) ?? now
        completion(Timeline(entries: [entry(at: now)], policy: .after(next)))
    }
}

// MARK: - Ring

// A closing ring, in the Activity-ring idiom.
//
// Sized with @ScaledMetric rather than a fixed frame, so the ring grows with
// the athlete's Dynamic Type setting instead of leaving its label to shrink
// inside a fixed circle. HIG requires text to scale; a ring whose label
// scales but whose geometry does not is the same failure one layer down.
struct Ring: View {
    let percent: Int
    let label: String
    let caption: String
    let tint: Color
    let known: Bool

    @ScaledMetric(relativeTo: .headline) private var diameter: Double = 62
    @ScaledMetric(relativeTo: .headline) private var thickness: Double = 8

    private var fraction: Double { min(1.0, max(0.0, Double(percent) / 100.0)) }

    var body: some View {
        VStack(spacing: 6) {
            ZStack {
                Circle()
                    .stroke(Color.primary.opacity(0.12), lineWidth: thickness)
                Circle()
                    .trim(from: 0, to: fraction)
                    .stroke(
                        known ? tint : Color.secondary.opacity(0.25),
                        style: StrokeStyle(lineWidth: thickness, lineCap: .round)
                    )
                    .rotationEffect(.degrees(-90))
                    // Marks the progress arc as the accent group, so the
                    // tinted Home Screen appearance keeps the ring readable
                    // instead of flattening ring and track to one colour.
                    .widgetAccentable()
                Text(known ? label : "—")
                    // A built-in text style, not .system(size:). This is what
                    // carries Dynamic Type; a hardcoded point size opts out
                    // of it entirely.
                    .font(.headline)
                    .fontDesign(.rounded)
                    .minimumScaleFactor(0.6)
                    .lineLimit(1)
            }
            .frame(width: diameter, height: diameter)

            Text(caption)
                // .caption2 is 11 pt at the default size — the iOS minimum.
                // The previous 9 pt was below the legibility floor.
                .font(.caption2)
                .fontWeight(.semibold)
                .foregroundStyle(.secondary)
        }
        .accessibilityElement(children: .ignore)
        .accessibilityLabel(caption.capitalized)
        .accessibilityValue(known ? "\\(label), \\(percent) percent of goal" : "Not available")
    }
}

// MARK: - Views per family

struct DailyWidgetView: View {
    @Environment(\\.widgetFamily) private var family
    var entry: Entry

    var body: some View {
        switch family {
        case .accessoryCircular:
            AccessoryCircularView(entry: entry)
        case .accessoryRectangular:
            AccessoryRectangularView(entry: entry)
        case .accessoryInline:
            // One line, no styling of its own — the system owns inline's
            // appearance entirely.
            Text(entry.snapshot.headline.isEmpty
                 ? entry.snapshot.waterLabel
                 : entry.snapshot.headline)
        default:
            SystemView(entry: entry)
        }
    }
}

struct SystemView: View {
    var entry: Entry

    private var snap: DashboardSnapshot { entry.snapshot }

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack(alignment: .top) {
                Ring(
                    percent: snap.waterPercent,
                    label: snap.waterLabel,
                    caption: "WATER",
                    tint: .blue,
                    known: true
                )
                Spacer(minLength: 4)
                Ring(
                    percent: snap.stepsPercent,
                    label: snap.stepsLabel,
                    caption: "STEPS",
                    tint: .green,
                    known: snap.stepsKnown
                )
            }

            // The one line worth reading, hidden when there is nothing to
            // say. Filler here would train the athlete to skip the line that
            // does mean something.
            if entry.isStale {
                Text("Open RepChamp to refresh")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .lineLimit(2)
            } else if !snap.headline.isEmpty {
                Text(snap.headline)
                    .font(.caption)
                    .fontWeight(.semibold)
                    .lineLimit(2)
                    .minimumScaleFactor(0.85)
            }

            if !entry.isStale && !snap.partnerLine.isEmpty {
                Text(snap.partnerLine)
                    .font(.caption2)
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
    }
}

// Lock Screen circular: one ring, no text label beside it — at this size the
// HIG asks for a single piece of information, and water is the one the
// athlete can act on right now.
struct AccessoryCircularView: View {
    var entry: Entry

    var body: some View {
        Gauge(value: min(1.0, Double(entry.snapshot.waterPercent) / 100.0)) {
            Image(systemName: "drop.fill")
        } currentValueLabel: {
            Text(entry.snapshot.waterLabel)
                .minimumScaleFactor(0.5)
        }
        .gaugeStyle(.accessoryCircular)
        .accessibilityLabel("Water")
        .accessibilityValue("\\(entry.snapshot.waterPercent) percent of goal")
    }
}

// Lock Screen rectangular: the headline plus both figures, as text. The
// vibrant rendering mode desaturates everything here, so this leans on
// hierarchy and SF Symbols rather than colour to separate the two numbers.
struct AccessoryRectangularView: View {
    var entry: Entry

    private var snap: DashboardSnapshot { entry.snapshot }

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(entry.isStale ? "Open RepChamp to refresh" : snap.headline)
                .font(.headline)
                .lineLimit(1)

            HStack(spacing: 8) {
                Label(snap.waterLabel, systemImage: "drop.fill")
                if snap.stepsKnown {
                    Label(snap.stepsLabel, systemImage: "figure.walk")
                }
            }
            .font(.caption)
            .lineLimit(1)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)
        .accessibilityElement(children: .combine)
    }
}

@main
struct RepChampDailyWidget: Widget {
    private let kind = "RepChampDailyWidget"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: Provider()) { entry in
            if #available(iOS 17.0, *) {
                DailyWidgetView(entry: entry)
                    // containerBackground is required from iOS 17: without it
                    // the system logs a warning and the widget renders with
                    // no background in some contexts.
                    .containerBackground(.fill.tertiary, for: .widget)
            } else {
                DailyWidgetView(entry: entry)
                    .padding()
            }
        }
        .configurationDisplayName("Today")
        .description("Your water and steps, and how your partner is doing.")
        .supportedFamilies([
            .systemSmall,
            .systemMedium,
            .accessoryCircular,
            .accessoryRectangular,
            .accessoryInline,
        ])
    }
}
`;

const INFO_PLIST = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>$(DEVELOPMENT_LANGUAGE)</string>
  <key>CFBundleDisplayName</key>
  <string>Today</string>
  <key>CFBundleExecutable</key>
  <string>$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key>
  <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleName</key>
  <string>$(PRODUCT_NAME)</string>
  <key>CFBundlePackageType</key>
  <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
  <key>CFBundleShortVersionString</key>
  <string>$(MARKETING_VERSION)</string>
  <key>CFBundleVersion</key>
  <string>$(CURRENT_PROJECT_VERSION)</string>
  <key>NSExtension</key>
  <dict>
    <key>NSExtensionPointIdentifier</key>
    <string>com.apple.widgetkit-extension</string>
  </dict>
</dict>
</plist>
`;

const ENTITLEMENTS = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.application-groups</key>
  <array>
    <string>${APP_GROUP}</string>
  </array>
</dict>
</plist>
`;

function write(file, contents) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents, 'utf8');
}

const withDailyWidgetIOS = (config) =>
  withDangerousMod(config, [
    'ios',
    (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, TARGET);
      write(path.join(dir, `${TARGET}.swift`), WIDGET_SWIFT);
      write(path.join(dir, 'Info.plist'), INFO_PLIST);
      write(path.join(dir, `${TARGET}.entitlements`), ENTITLEMENTS);
      return cfg;
    },
  ]);

module.exports = withDailyWidgetIOS;
module.exports.APP_GROUP = APP_GROUP;
module.exports.SNAPSHOT_KEY = SNAPSHOT_KEY;
module.exports.TARGET = TARGET;
