/**
 * The iOS daily-dashboard widget.
 *
 * `ios/` is gitignored and regenerated by `expo prebuild`, so — exactly like
 * the Android widget — the only durable home for this is a config plugin that
 * writes the sources during prebuild.
 *
 * ## What this plugin does and does not do
 *
 * It writes the Swift sources and a matching Info.plist into
 * `ios/RepChampDailyWidget/`, so the extension's code is version-controlled
 * and regenerated on every prebuild.
 *
 * It does **not** create the Xcode target. Adding a second target means
 * rewriting `project.pbxproj` — a fragile, undocumented format where a bad
 * edit corrupts the project rather than failing loudly — and an App Extension
 * additionally needs an App Group entitlement, which needs an Apple Developer
 * team id. Neither is configured here (`app.json` has no `appleTeamId`), so a
 * plugin that claimed to wire this up would be writing a target that cannot
 * be signed.
 *
 * The honest seam is therefore: this plugin owns the *code*, and the target
 * is added once in Xcode (or by `expo-apple-targets` once a team id exists).
 * `WIDGET_SETUP_IOS.md` records the exact steps. Everything the extension
 * reads — the payload keys, the copy, the thresholds — comes from
 * `src/domain/dashboardSnapshot.ts` and is unit-tested there, so the Swift
 * below stays a renderer with no decisions of its own.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** The target name, the folder name, and the scheme all match. */
const TARGET = 'RepChampDailyWidget';

/**
 * The App Group the app and the widget share.
 *
 * An extension runs in its own process with its own container, so
 * `UserDefaults.standard` in the widget is *not* the app's — the group
 * suite is the only way the payload crosses. Inert until the group is
 * registered against a real team id; `defaults(for:)` falls back to standard
 * defaults so the widget still builds and renders its placeholder.
 */
const APP_GROUP = 'group.gg.repchamp.app';

const SNAPSHOT_KEY = 'repchamp.widget.dashboard.v1';

const WIDGET_SWIFT = `import WidgetKit
import SwiftUI

// The payload the app publishes. Mirrors DashboardSnapshot in
// src/domain/dashboardSnapshot.ts — every label is built and tested there, so
// nothing here decides what the athlete reads.
struct DashboardSnapshot: Decodable {
    var waterLabel: String = ""
    var waterPercent: Int = 0
    var waterMet: Bool = false
    var stepsLabel: String = ""
    var stepsPercent: Int = 0
    var stepsMet: Bool = false
    var stepsKnown: Bool = false
    var partnerLine: String = ""
    var headline: String = ""
    var updatedAt: Double = 0

    // Shown in the widget gallery, where the system renders the view without
    // ever calling the timeline provider. Without real-looking values the
    // card is hollow at the exact moment someone decides whether to add it.
    static let preview = DashboardSnapshot(
        waterLabel: "1.5 L", waterPercent: 75, waterMet: false,
        stepsLabel: "8,432", stepsPercent: 105, stepsMet: true,
        stepsKnown: true,
        partnerLine: "Sam had 1.5 L today",
        headline: "500 ml of water to go",
        updatedAt: Date().timeIntervalSince1970 * 1000
    )
}

enum SnapshotStore {
    // The app group's suite, falling back to standard defaults so the
    // extension still builds and previews before the group is registered.
    static func defaults() -> UserDefaults {
        UserDefaults(suiteName: "${APP_GROUP}") ?? .standard
    }

    static func load() -> DashboardSnapshot? {
        guard let raw = defaults().string(forKey: "${SNAPSHOT_KEY}"),
              let data = raw.data(using: .utf8),
              let decoded = try? JSONDecoder().decode(DashboardSnapshot.self, from: data)
        else { return nil }
        return decoded
    }
}

struct Entry: TimelineEntry {
    let date: Date
    let snapshot: DashboardSnapshot
    let isStale: Bool
}

struct Provider: TimelineProvider {
    // Twelve hours, matching DASHBOARD_STALE_AFTER_MS. A widget that shows
    // yesterday's numbers as if they were today's is worse than one that
    // admits it has lost touch.
    private static let staleAfter: TimeInterval = 12 * 60 * 60

    private func entry(at date: Date) -> Entry {
        guard let snap = SnapshotStore.load() else {
            return Entry(date: date, snapshot: .preview, isStale: false)
        }
        let age = date.timeIntervalSince1970 - (snap.updatedAt / 1000)
        return Entry(date: date, snapshot: snap, isStale: age > Self.staleAfter)
    }

    func placeholder(in context: Context) -> Entry {
        Entry(date: Date(), snapshot: .preview, isStale: false)
    }

    func getSnapshot(in context: Context, completion: @escaping (Entry) -> Void) {
        completion(entry(at: Date()))
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> Void) {
        // One entry now, refreshed in an hour. The app also calls
        // WidgetCenter.reloadTimelines whenever it publishes, so this cadence
        // is the floor rather than the mechanism.
        let now = Date()
        let next = Calendar.current.date(byAdding: .hour, value: 1, to: now) ?? now
        completion(Timeline(entries: [entry(at: now)], policy: .after(next)))
    }
}

// A closing ring. The same idiom as the in-app card, so the widget reads as
// the same product rather than a separate one.
struct Ring: View {
    let percent: Int
    let label: String
    let caption: String
    let tint: Color
    let known: Bool

    private var fraction: Double { min(1.0, max(0.0, Double(percent) / 100.0)) }

    var body: some View {
        VStack(spacing: 6) {
            ZStack {
                Circle()
                    .stroke(Color.primary.opacity(0.12), lineWidth: 8)
                Circle()
                    .trim(from: 0, to: fraction)
                    .stroke(
                        known ? tint : Color.secondary.opacity(0.25),
                        style: StrokeStyle(lineWidth: 8, lineCap: .round)
                    )
                    .rotationEffect(.degrees(-90))
                Text(known ? label : "—")
                    .font(.system(size: 15, weight: .bold, design: .rounded))
                    .minimumScaleFactor(0.6)
                    .lineLimit(1)
            }
            .frame(width: 62, height: 62)

            Text(caption)
                .font(.system(size: 9, weight: .bold))
                .kerning(0.8)
                .foregroundStyle(.secondary)
        }
    }
}

struct DailyWidgetView: View {
    var entry: Entry

    private var snap: DashboardSnapshot { entry.snapshot }

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack(alignment: .top) {
                Ring(
                    percent: snap.waterPercent,
                    label: snap.waterLabel,
                    caption: "WATER",
                    tint: .blue,
                    known: true
                )
                Spacer(minLength: 4)
                Ring(
                    percent: snap.stepsPercent,
                    label: snap.stepsLabel,
                    caption: "STEPS",
                    tint: .green,
                    known: snap.stepsKnown
                )
            }

            // The one line worth reading, hidden when there is nothing to
            // say. Filler here would train the athlete to skip the line that
            // does mean something.
            if entry.isStale {
                Text("Open RepChamp to refresh")
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundStyle(.secondary)
                    .lineLimit(2)
            } else if !snap.headline.isEmpty {
                Text(snap.headline)
                    .font(.system(size: 11, weight: .bold))
                    .lineLimit(2)
                    .minimumScaleFactor(0.85)
            }

            if !entry.isStale && !snap.partnerLine.isEmpty {
                Text(snap.partnerLine)
                    .font(.system(size: 10, weight: .medium))
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
    }
}

@main
struct RepChampDailyWidget: Widget {
    private let kind = "RepChampDailyWidget"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: Provider()) { entry in
            if #available(iOS 17.0, *) {
                DailyWidgetView(entry: entry)
                    .containerBackground(.fill.tertiary, for: .widget)
            } else {
                DailyWidgetView(entry: entry)
                    .padding()
            }
        }
        .configurationDisplayName("Today")
        .description("Your water and steps, and how your partner is doing.")
        .supportedFamilies([.systemSmall, .systemMedium])
    }
}
`;

const INFO_PLIST = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>$(DEVELOPMENT_LANGUAGE)</string>
  <key>CFBundleDisplayName</key>
  <string>Today</string>
  <key>CFBundleExecutable</key>
  <string>$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key>
  <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleName</key>
  <string>$(PRODUCT_NAME)</string>
  <key>CFBundlePackageType</key>
  <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
  <key>CFBundleShortVersionString</key>
  <string>$(MARKETING_VERSION)</string>
  <key>CFBundleVersion</key>
  <string>$(CURRENT_PROJECT_VERSION)</string>
  <key>NSExtension</key>
  <dict>
    <key>NSExtensionPointIdentifier</key>
    <string>com.apple.widgetkit-extension</string>
  </dict>
</dict>
</plist>
`;

const ENTITLEMENTS = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.application-groups</key>
  <array>
    <string>${APP_GROUP}</string>
  </array>
</dict>
</plist>
`;

function write(file, contents) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents, 'utf8');
}

const withDailyWidgetIOS = (config) =>
  withDangerousMod(config, [
    'ios',
    (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, TARGET);
      write(path.join(dir, `${TARGET}.swift`), WIDGET_SWIFT);
      write(path.join(dir, 'Info.plist'), INFO_PLIST);
      write(path.join(dir, `${TARGET}.entitlements`), ENTITLEMENTS);
      return cfg;
    },
  ]);

module.exports = withDailyWidgetIOS;
module.exports.APP_GROUP = APP_GROUP;
module.exports.SNAPSHOT_KEY = SNAPSHOT_KEY;
module.exports.TARGET = TARGET;
